name: Push to TestPyPy

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: TestPyPi
      url: https://test.pypi.org/p/image-resolution-is-even
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: python -m pip install build pytest

      - name: Build package
        run: python -m build

      - name: Install package
        run: python -m pip install .[dev]

      - name: Test package
        run: python -m pytest

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1.8
        with:
          repository-url: ${{ secrets.PYPI_REPOSITORY }}
